SET NOCOUNT ON;

-- 1. 抓取入库明细 (加入你的严苛过滤条件，消灭 1.5 万行草稿噪音)
SELECT 
    CAST(CAST(A.DHOPDONGID AS VARCHAR) + ';' + CAST(A.TYPE AS VARCHAR) + ';' + CAST(B.DINH_DANH_HANG_HOA AS VARCHAR) + ';' AS NVARCHAR(100)) CKEYS, 
    A.DHOPDONGID, A.TYPE, A.SO_PHIEU, A.NGAY_PHIEU, A.DPHIEUID, A.SO_HD, A.NGAY_HD, A.MA_NGUON, A.MA_NT, A.TY_GIA_VND,
    B.DPHIEU_HANGID, B.SO_TK, CAST(B.NGAY_DK AS DATE) AS NGAY_DK, B.NGAY_VAO_RA, B.DINH_DANH_HANG_HOA, B.MA_SP, B.TEN_SP, B.STTHANG, 
    ISNULL(B.MA_NUOC, 'VN') AS MA_NUOC, B.SO_LUONG, B.MA_DVT, B.DON_GIA AS GIA_NHAP, B.TRI_GIA, B.MA_HS
INTO #NHAP 
FROM DPHIEU A 
INNER JOIN DPHIEU_HANG B ON (A.DPHIEUID = B.DPHIEUID AND ISNULL(B.IS_HUY, 0) = 0) 
WHERE A.MA_KNQ ='VNNSL' 
  AND A._XORN = 'N' 
  AND ISNULL(A.HUY_TRANG_THAI, 0) = 0
  -- 【核心介入】：排除草稿，必须是正式报关 (对齐你的 14389 逻辑)
  AND ISNULL(A.TRANG_THAI, '') NOT IN ('T', '0', '1', 'H')
  AND (A.MESSAGEID IS NOT NULL OR A.NGAY_DK IS NOT NULL OR A.SO_PHIEU LIKE '%RH%')
  -- 强制 12 位纯数字报关单过滤
  AND LTRIM(RTRIM(REPLACE(CAST(A.SOTK AS VARCHAR(50)), '.0', ''))) LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]';

-- 2. 抓取出库汇总 (同样排除草稿，保证核销基数准确)
SELECT 
    CAST('' AS NVARCHAR(100)) CKEYS, 
    A.TYPE, A.DHOPDONGID, A.SO_HD, MAX(A.NGAY_PHIEU) NGAY_XUAT, B.SO_PHIEU_N, B.MA_SP, B.DINH_DANH_HANG_HOA, ROUND(SUM(B.SO_LUONG),4) SO_LUONG
INTO #XUAT 
FROM DPHIEU A 
INNER JOIN DPHIEU_HANG B ON (A.DPHIEUID = B.DPHIEUID AND ISNULL(B.IS_HUY, 0) = 0) 
WHERE A.MA_KNQ ='VNNSL' 
  AND A._XORN = 'X' 
  AND ISNULL(A.HUY_TRANG_THAI, 0) = 0
  AND ISNULL(A.TRANG_THAI, '') NOT IN ('T', '0', '1', 'H')
  AND (A.MESSAGEID IS NOT NULL OR A.NGAY_DK IS NOT NULL)
GROUP BY A.TYPE, A.DHOPDONGID, A.SO_HD, B.SO_PHIEU_N, B.MA_SP, B.DINH_DANH_HANG_HOA;

-- 3. 关联进出库，生成报表所需的动态核销字段
UPDATE #XUAT SET CKEYS = CAST(CAST(A.DHOPDONGID AS VARCHAR) + ';' + CAST(A.TYPE AS VARCHAR) + ';' + CAST(B.DINH_DANH_HANG_HOA AS VARCHAR) + ';' AS NVARCHAR(100))
FROM #XUAT B INNER JOIN #NHAP A ON A.SO_PHIEU = B.SO_PHIEU_N AND A.MA_SP = B.MA_SP AND A.DINH_DANH_HANG_HOA = B.DINH_DANH_HANG_HOA;

SELECT 
    ROW_NUMBER() OVER(PARTITION BY CKEYS ORDER BY NGAY_PHIEU, DPHIEUID, DPHIEU_HANGID) AS STT, 
    *, 0*SO_LUONG AS LUONG_XUAT, 0*SO_LUONG AS LUONG_TON, CAST(NULL AS DATE) NGAY_XUAT, CAST(NULL AS INT) AS SO_NGAY_TON 
INTO #NHAP2 
FROM #NHAP;

-- 4. 执行更新，算出真实出库与余量
UPDATE #NHAP2 SET LUONG_XUAT = X.SO_LUONG, NGAY_XUAT = X.NGAY_XUAT
FROM #NHAP2 N INNER JOIN (SELECT CKEYS, SUM(SO_LUONG) AS SO_LUONG, MAX(NGAY_XUAT) AS NGAY_XUAT FROM #XUAT GROUP BY CKEYS) X ON N.CKEYS = X.CKEYS;

UPDATE #NHAP2 SET LUONG_TON = SO_LUONG - LUONG_XUAT;
UPDATE #NHAP2 SET SO_NGAY_TON = DATEDIFF(DAY, NGAY_PHIEU, GETDATE());

-- 5. 最终结果提取 (严格控制大于 0)
SELECT 
    STT, 
    LTRIM(RTRIM(REPLACE(CAST(SO_TK AS VARCHAR(50)), '.0', ''))) AS [Số TK nhập], 
    CONVERT(VARCHAR(10), NGAY_DK, 103) AS [Ngày TK], 
    SO_PHIEU AS [Số PNK], 
    CONVERT(VARCHAR(10), NGAY_PHIEU, 103) AS [Ngày NK], 
    SO_HD AS [Số hợp đồng], 
    CONVERT(VARCHAR(10), NGAY_HD, 103) AS [Ngày hợp đồng], 
    MA_SP AS [Mã hàng], 
    TEN_SP AS [Tên hàng], 
    DINH_DANH_HANG_HOA AS [Định danh hàng hóa], 
    MA_NUOC AS [Xuất xứ], 
    MA_HS AS [Mã HS], 
    SO_LUONG AS [Lượng], 
    GIA_NHAP AS [Đơn giá], 
    MA_DVT AS [Đơn vị tính], 
    LUONG_XUAT AS [Lượng xuất], 
    LUONG_TON AS [SL Tồn], 
    (LUONG_TON * GIA_NHAP) AS [Trị Giá Tồn], 
    MA_NT AS [Mã NT], 
    CONVERT(VARCHAR(10), NGAY_PHIEU, 103) AS [Ngày nhập], 
    CONVERT(VARCHAR(10), NGAY_XUAT, 103) AS [Ngày xuất], 
    SO_NGAY_TON AS [Số ngày tồn]
FROM #NHAP2 
WHERE LUONG_TON > 0.001
ORDER BY NGAY_PHIEU DESC;

-- 6. 清理内存
DROP TABLE #NHAP;
DROP TABLE #XUAT;
DROP TABLE #NHAP2;